name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v4     
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   
          
      - name: Restore
        run: dotnet restore
              
      - name: Build
        run: dotnet build --no-restore --configuration Release
             
      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal             
      